values <- read.csv("AutoOnline_values.csv", sep = ";")
labels <- read.csv("AutoOnline_labels.csv", sep = ";")

colnames(values)[1] <- 'qnrnumb'
colnames(labels)[1] <- 'qnrnumb'

yes.no_vector <- c('Yes', 'No')
often_vector <- c('Never', 'Almost never', 'Occasionally', 'Often', 'Very Often')
agree_vector <- c('Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree')
no.yes_vector <- c('No', 'Yes')
how.much_vector <- c('A great deal better', 'Much better', 'Somewhat better', 'Just a bit better')
marital_vector <- c('Single', 'Married', 'Widowed', 'Divorced', 'Seperated')
education_vector <- c('Less than high school', 'High school', 'Some college', 'Undergraduate degree', 'Graduate degree', 'Other')
race_vector <- c('Caucasian', 'Black', 'Asian', 'American Indian', 'Hispanic', 'Other')
income_vector <- c('Under $35,000', '$50,000 - $65,000', '$65,000 - $80,000', '$80,000 - $95,000', '$95,000 - $110,000', 'Over $110,000')
gender_vector <- c('Male', 'Female')

labels$visit <- factor(labels$visit, levels = yes.no_vector)
labels$howoft <- factor(labels$howoft, levels = often_vector, order = TRUE)
labels$likenet <- factor(labels$likenet, levels = agree_vector, order = TRUE)
labels$research <- factor(labels$research, levels = agree_vector, order = TRUE)
labels$safeweb <- factor(labels$safeweb, levels = agree_vector, order = TRUE)
labels$goodtool <- factor(labels$goodtool, levels = agree_vector, order = TRUE)
labels$notouse <- factor(labels$notouse, levels = agree_vector, order = TRUE)
labels$another <- factor(labels$another, levels = agree_vector, order = TRUE)
labels$likeproc <- factor(labels$likeproc, levels = agree_vector, order = TRUE)
labels$hassle <- factor(labels$hassle, levels = agree_vector, order = TRUE)
labels$friend <- factor(labels$friend, levels = no.yes_vector)
labels$billbrd <- factor(labels$billbrd, levels = no.yes_vector)
labels$banner <- factor(labels$banner, levels = no.yes_vector)
labels$surfing <- factor(labels$surfing, levels = no.yes_vector)
labels$sengine <- factor(labels$sengine, levels = no.yes_vector)
labels$tv <- factor(labels$tv, levels = no.yes_vector)
labels$theater <- factor(labels$theater, levels = no.yes_vector)
labels$nwspaper <- factor(labels$nwspaper, levels = no.yes_vector)
labels$other <- factor(labels$other, levels = no.yes_vector)
labels$easyuse <- factor(labels$easyuse, levels = agree_vector, order = TRUE)
labels$helpful <- factor(labels$helpful, levels = agree_vector, order = TRUE)
labels$positive <- factor(labels$positive, levels = agree_vector, order = TRUE)
labels$useonly <- factor(labels$useonly, levels = agree_vector, order = TRUE)
labels$influenc <- factor(labels$influenc, levels = agree_vector, order = TRUE)
labels$secure <- factor(labels$secure, levels = agree_vector, order = TRUE)
labels$didbuy <- factor(labels$didbuy, levels = yes.no_vector)
labels$better <- factor(labels$better, levels = yes.no_vector)
labels$howmuch <- factor(labels$howmuch, levels = how.much_vector, order = TRUE)
labels$safe <- factor(labels$safe, levels = agree_vector, order = TRUE)
labels$wanttest <- factor(labels$wanttest, levels = agree_vector, order = TRUE)
labels$price <- factor(labels$price, levels = agree_vector, order = TRUE)
labels$tradein <- factor(labels$tradein, levels = agree_vector, order = TRUE)
labels$handson <- factor(labels$handson, levels = agree_vector, order = TRUE)
labels$checkit <- factor(labels$checkit, levels = agree_vector, order = TRUE)
labels$marital <- factor(labels$marital, levels = marital_vector)
labels$educate <- factor(labels$educate, levels = education_vector)
labels$race <- factor(labels$race, levels = race_vector)
labels$income <- factor(labels$income, levels = income_vector, order = TRUE)
labels$gender <- factor(labels$gender, levels = gender_vector)

data <- labels

summary(data)